import { Footer } from "./components/Footer"
import NavBar from "./components/NavBar"
import React from "react"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet" />
      <body>
        <header>
          <NavBar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  )
}